spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/systgestionformation
    username: sgf
    password: sgf123
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
